:set prompt "\ESC[1;35m\x03BB> \ESC[m"
:set prompt-cont "\ESC[1;35m > \ESC[m"

:set -XRankNTypes
:set -XMultiWayIf
:set -XInstanceSigs
:set -XLambdaCase
:set -XOverloadedStrings
:set -XMultiParamTypeClasses
:set -XFunctionalDependencies
:set -XViewPatterns
:set -XDerivingVia
:set -XExistentialQuantification
:set -XKindSignatures
:set -XTypeFamilies
:set -XDataKinds
:set -XPolyKinds
:set -XGADTs
:set -XConstraintKinds
:set -XFlexibleContexts
