encryption:
    tag: KEYRING

services:
  microsoft:
    client_id: 18da2bc3-146a-4581-8c92-27dc7b9954a0
    client_secret: ""
    redirect_uri: http://localhost:8398
    auth_scope: https://outlook.office.com/IMAP.AccessAsUser.All
      https://outlook.office.com/SMTP.Send
      offline_access
    tenant: common

