# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/

jobs: 8

ghc-options:
  "$everything": -O2

templates:
  params:
    author-name: Poscat
    author-email: poscat@mail.poscat.moe
    github-username: poscat0x04

color: always

default-template: library

recommend-stack-upgrade: false

allow-newer: true

